### PR TITLE
Feed blogpost

### PR DESCRIPTION
**Pull request by 7596ff**

### CODE REVIEW

**Comment by howardchung** [comment]
Do we want to put the docs in this blog post?

**Comment by 7596ff** [comment]
I think a link to them will be just fine, when the core pr is merged the link here will work

**Comment by howardchung** [comment]
I mean making the blog post essentially the docs, like RJackson's blog post.  I imagine the visibility will be lower in the odota/core repo.

**Comment by 7596ff** [comment]
I found his post through a link from the node-dota2 repository way back when. I feel like people who will need the docs will know how to find them.

**Comment by howardchung** [comment]
OK.  Will wait on merging this until the service is deployed and working

**Pull request closed without merging**
